#:kivy 1.7.1
<SayThis>:
	orientation: 'vertical'
	video_obj: video_obj
	Video:
		id: video_obj
		source: 'http://192.168.1.106/tep.mp4'
		volume: 0
	BoxLayout:
		orientation: 'horizontal'
		size_hint: 1,None
		height: play_button.height	
		Button:
			id: play_button
			text:'Play'
			size_hint: 1,None
			on_press: root.playvideo()
		Button:
			text:'Pause'
			size_hint: 1,None
			on_press: root.pausevideo()
